version: '2'
services:
    api:
        image: ricardomlima/thewall-api
        volumes:
            - ./api:/home
        expose:
            - "8000"
        ports:
            - "80:8000"
    frontend:
        image: ricardomlima/thewall-frontend
        volumes:
            - ./frontend:/home
        ports:
            - "3000:3000"
