version: '2'
services:
    api:
        image: ricardomlima/thewall-api
        volumes:
            - ./api:/home
            - ./api/db.sqlite3:/home/db.sqlite3
        expose:
            - "8000"
        ports:
            - "80:8000"
    frontend:
        image: ricardomlima/thewall-frontend
        volumes:
            - ./frontend:/home
            - /home/node_modules
        ports:
            - "3000:3000"
