version: '2'
services:
    api:
        build: ./api
        image: ricardomlima/thewall-api
        volumes:
            - ./api:/home
        expose:
            - "8000"
        ports:
            - "80:8000"
